from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class SetupType(StrEnum):
    ONE_TO_TWO = "ONE_TO_TWO"
    HIGH_BOARD = "HIGH_BOARD"
    WEAK_TO_STRONG = "WEAK_TO_STRONG"


class CandidateGrade(StrEnum):
    A1 = "A1"
    A2 = "A2"
    B_CONFIRMATION = "B_CONFIRMATION"
    B_DISAGREEMENT = "B_DISAGREEMENT"
    B_CONSENSUS_RISK = "B_CONSENSUS_RISK"
    B_HIGH_QUALITY = "B_HIGH_QUALITY"
    B_LEADERSHIP_CHALLENGED = "B_LEADERSHIP_CHALLENGED"
    B_ECOSYSTEM_PENDING = "B_ECOSYSTEM_PENDING"
    C_NIGHT_DEGRADED = "C_NIGHT_DEGRADED"
    C_AUCTION_EMERGENT = "C_AUCTION_EMERGENT"
    C_HIGHBOARD_DEGRADED = "C_HIGHBOARD_DEGRADED"
    C_LEADERSHIP_LOST = "C_LEADERSHIP_LOST"
    DROP = "DROP"


class ValidationState(StrEnum):
    UNVALIDATED = "UNVALIDATED"
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    FALSIFIED = "FALSIFIED"
    INVALID = "INVALID"
    HARD_INVALID = "HARD_INVALID"


class AuthenticityState(StrEnum):
    UNKNOWN = "UNKNOWN"
    AUTHENTIC = "AUTHENTIC"
    HEALTHY_DISAGREEMENT = "HEALTHY_DISAGREEMENT"
    HEALTHY_DISAGREEMENT_PENDING = "HEALTHY_DISAGREEMENT_PENDING"
    SUSPICIOUS = "SUSPICIOUS"
    FAKE_STRONG = "FAKE_STRONG"


class ExecutionState(StrEnum):
    IDLE = "IDLE"
    ARMED = "ARMED"
    WAITING = "WAITING"
    WAIT = "WAIT"
    EXECUTE = "EXECUTE"
    CANCELLED = "CANCELLED"
    HARD_CANCELLED = "HARD_CANCELLED"
    EXPIRED = "EXPIRED"


class DataQualityState(StrEnum):
    GOOD = "GOOD"
    DEGRADED = "DEGRADED"
    BROKEN = "BROKEN"


class LeadershipState(StrEnum):
    LEADER = "LEADER"
    CORE = "CORE"
    FRONT_ROW = "FRONT_ROW"
    FOLLOWER = "FOLLOWER"
    DOMINANT = "DOMINANT"
    RETAINED = "RETAINED"
    CHALLENGED = "CHALLENGED"
    LOST = "LOST"
    UNKNOWN = "UNKNOWN"


class HighBoardEcosystem(StrEnum):
    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    NEGATIVE = "NEGATIVE"
    SEVERE_NEGATIVE = "SEVERE_NEGATIVE"


class WeakToStrongType(StrEnum):
    WEAK_BOARD_TO_STRONG = "WEAK_BOARD_TO_STRONG"
    BROKEN_BOARD_TO_STRONG = "BROKEN_BOARD_TO_STRONG"
    CORE_NEGATIVE_FEEDBACK_REPAIR = "CORE_NEGATIVE_FEEDBACK_REPAIR"


class WeaknessSource(StrEnum):
    BOARD_STRUCTURE = "BOARD_STRUCTURE"
    SECTOR_DRAG = "SECTOR_DRAG"
    MARKET_DRAG = "MARKET_DRAG"
    LEADERSHIP_LOSS = "LEADERSHIP_LOSS"
    LIQUIDITY = "LIQUIDITY"
    EVENT = "EVENT"


class WeaknessResolution(StrEnum):
    TRUE = "TRUE"
    PARTIAL = "PARTIAL"
    FALSE = "FALSE"


class IdentityRecoveryState(StrEnum):
    TRUE = "TRUE"
    PARTIAL = "PARTIAL"
    FALSE = "FALSE"


class OpenPhase(StrEnum):
    PRE_OPEN = "PRE_OPEN"
    OPEN_SHOCK = "OPEN_SHOCK"
    OPEN_CONFIRM = "OPEN_CONFIRM"
    FOLLOW_THROUGH = "FOLLOW_THROUGH"
    EXPIRED = "EXPIRED"


class ExecutionMode(StrEnum):
    OPEN_CONTINUATION = "OPEN_CONTINUATION"
    PULLBACK_RECLAIM = "PULLBACK_RECLAIM"
    BREAKOUT_CONFIRM = "BREAKOUT_CONFIRM"
    LEADER_CONTINUATION = "LEADER_CONTINUATION"
    LEADER_DIVERGENCE_RECLAIM = "LEADER_DIVERGENCE_RECLAIM"
    LEADERSHIP_RETAKE = "LEADERSHIP_RETAKE"
    REPAIR_CONTINUATION = "REPAIR_CONTINUATION"
    REPAIR_PULLBACK_RECLAIM = "REPAIR_PULLBACK_RECLAIM"
    IDENTITY_BREAKOUT = "IDENTITY_BREAKOUT"


class AuctionOpenConsistency(StrEnum):
    CONFIRMED = "CONFIRMED"
    PARTIAL = "PARTIAL"
    FALSIFIED = "FALSIFIED"


class SignalTradability(StrEnum):
    VALID_AND_TRADABLE = "VALID_AND_TRADABLE"
    VALID_BUT_EXTENDED = "VALID_BUT_EXTENDED"
    INVALID = "INVALID"


class AccountAuctionState(StrEnum):
    EXECUTION_READY = "EXECUTION_READY"
    WAIT_OPEN = "WAIT_OPEN"
    CASH = "CASH"


class OutcomeClass(StrEnum):
    CLEAN_SUCCESS = "CLEAN_SUCCESS"
    UGLY_SUCCESS = "UGLY_SUCCESS"
    GOOD_NON_LIMIT = "GOOD_NON_LIMIT"
    FLAT_NO_EDGE = "FLAT_NO_EDGE"
    FAST_FAILURE = "FAST_FAILURE"
    SLOW_FAILURE = "SLOW_FAILURE"


class OutcomeDiagnostic(StrEnum):
    FP_EXPECTATION = "FP_EXPECTATION"
    FP_AUTHENTICITY = "FP_AUTHENTICITY"
    FP_CONTEXT = "FP_CONTEXT"
    FP_LIQUIDITY = "FP_LIQUIDITY"
    FP_EXECUTION = "FP_EXECUTION"
    FN_NIGHT_SELECTION = "FN_NIGHT_SELECTION"
    FN_AUCTION_FILTER = "FN_AUCTION_FILTER"
    FN_OPEN_CANCEL = "FN_OPEN_CANCEL"


class StorageLayer(StrEnum):
    RAW = "raw"
    DERIVED = "derived"
    DECISION = "decisions"
    OUTCOME = "outcomes"


class FieldAcceptanceStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PENDING = "PENDING"
    REJECTED = "REJECTED"


class CircuitBreakerState(StrEnum):
    CLOSED = "CLOSED"
    DEGRADED = "DEGRADED"
    OPEN = "OPEN"


class DailyStage(StrEnum):
    PRE_FLIGHT = "PRE_FLIGHT"
    AUCTION = "AUCTION"
    FINAL_DECISION = "FINAL_DECISION"
    OPEN_EXECUTION = "OPEN_EXECUTION"
    INTRADAY_IDLE = "INTRADAY_IDLE"
    AFTER_CLOSE = "AFTER_CLOSE"
    HALTED = "HALTED"


class SourceAgreementState(StrEnum):
    AGREED = "AGREED"
    DISAGREEMENT = "DISAGREEMENT"
    CRITICAL = "CRITICAL"
    INSUFFICIENT = "INSUFFICIENT"


class PermissionState(StrEnum):
    ALLOW = "ALLOW"
    REDUCE = "REDUCE"
    DENY = "DENY"


class ThresholdStatus(StrEnum):
    STRUCTURAL = "STRUCTURAL"
    SEED = "SEED"
    CALIBRATED = "CALIBRATED"
    RETIRED = "RETIRED"


class ReplayMode(StrEnum):
    FULL_SPEED = "FULL_SPEED"
    REAL_TIME = "REAL_TIME"
    STEP = "STEP"
    CHECKPOINT = "CHECKPOINT"


class AuctionPhase(StrEnum):
    PRE_AUCTION = "PRE_AUCTION"
    SCOUTING = "SCOUTING"
    VALIDATING = "VALIDATING"
    FINALIZING = "FINALIZING"
    FINAL = "FINAL"
    OPEN_EXECUTION = "OPEN_EXECUTION"


class BenchmarkStatus(StrEnum):
    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT = "INSUFFICIENT"


class FakeStrongFlag(StrEnum):
    PRE20_MIRAGE = "PRE20_MIRAGE"
    POST20_CONTINUOUS_DECAY = "POST20_CONTINUOUS_DECAY"
    PRICE_WITHOUT_LIQUIDITY = "PRICE_WITHOUT_LIQUIDITY"
    ISOLATED_STRENGTH = "ISOLATED_STRENGTH"
    LAST_SECOND_SPIKE = "LAST_SECOND_SPIKE"
    FAKE_LEADER_ISOLATION = "FAKE_LEADER_ISOLATION"
    FAKE_HEIGHT_PREMIUM = "FAKE_HEIGHT_PREMIUM"
    FAKE_ONE_WORD_CONSENSUS = "FAKE_ONE_WORD_CONSENSUS"
    OPEN_ONLY_REPAIR = "OPEN_ONLY_REPAIR"
    ISOLATED_REPAIR = "ISOLATED_REPAIR"
    NO_IDENTITY_RECOVERY = "NO_IDENTITY_RECOVERY"
    LIQUIDITY_FAKE_REPAIR = "LIQUIDITY_FAKE_REPAIR"
    REPAIR_AND_FADE = "REPAIR_AND_FADE"
