from enum import Enum


class ReasonCode(str, Enum):
    OUTSIDE_NIGHT_POOL = "OUTSIDE_NIGHT_POOL"
    MARKET_PERMISSION_DENIED = "MARKET_PERMISSION_DENIED"
    SETUP_PERMISSION_DENIED = "SETUP_PERMISSION_DENIED"
    REGULATORY_HARD_INVALID = "REGULATORY_HARD_INVALID"
    DATA_QUALITY_BROKEN = "DATA_QUALITY_BROKEN"
    MARKET_VALIDATION_FAILED = "MARKET_VALIDATION_FAILED"
    CANDIDATE_VALIDATION_FAILED = "CANDIDATE_VALIDATION_FAILED"
    AUTHENTICITY_FAILED = "AUTHENTICITY_FAILED"
    SETUP_REQUIREMENT_FAILED = "SETUP_REQUIREMENT_FAILED"
    SCORE_BELOW_GATE = "SCORE_BELOW_GATE"
    CROSS_SETUP_RANK_FAILED = "CROSS_SETUP_RANK_FAILED"
    POSITION_PERMISSION_DENIED = "POSITION_PERMISSION_DENIED"
    HARD_CANCEL_STICKY = "HARD_CANCEL_STICKY"
    ARMED_NOT_EXECUTED = "ARMED_NOT_EXECUTED"
